### ISSUE TITLE
`swjs_create_typed_array` error on `carton test`

### ISSUE THREAD

**Issue by ephemer** [swiftwasm/carton#322] opened 2022-04-25 16:57 UTC
Hey there, thanks for `carton`! We (flowkey) have been a sponsor for a while but I only got to really test things out today for the first time. I was able to get one of our fairly complex internal libraries building with it within a few hours (removing dependencies on Dispatch and Foundation).

Now I'm trying to get the tests running and so far I've been getting the following error: 

```
carton test

Error: Process failed with non-zero exit status and following output:
 and following error output:
error: failed to run `/xyz/abc/.build/wasm32-unknown-wasi/debug/...PackageTests.wasm`
╰─▶ 1: Error while importing "javascript_kit"."swjs_create_typed_array": unknown import. Expected Function(FunctionType { params: [I32, I32, I32], results: [I32] })
```

`swift test` works fine on the same project.

I have a javascript kit dependency like so: `.package(url: "https://github.com/swiftwasm/JavaScriptKit", from: "0.13.0")` and it's a dependency of my test target like this: `.product(name: "JavaScriptKit", package: "JavaScriptKit")`.

Is there something obvious I'm missing or is it more likely to be a case of "disable all tests and enable them one-by-one until something turns up"? I will try the latter tomorrow but thought I'd write here in case something had changed in a recent version of JavaScriptKit or something.

**Comment by MaxDesiatov** [comment] 2022-04-25 19:29
cc @kateinoigakukun @j-f1

**Comment by ephemer** [comment] 2022-04-26 06:49
Maybe it's because I have no modules that actually import JavaScriptKit (even if it is listed as a dependency). I will give this a shot later

**Comment by MaxDesiatov** [comment] 2022-04-26 08:19
Thanks. In case the error persists, could you share some isolated sample code for reproduction?

**Comment by ephemer** [comment] 2022-04-26 12:33
FYI I ran `carton init`, commented out all the mac-specific code in the dummy test file it creates (which fails to build for wasm), fixed the duplicate `main.swift` issue, and ran `carton test`, and I get the same issue mentioned in the original post. That's about as minimal as you can get – there is literally no code in either than library or the test in this case and the same issue occurs. @MaxDesiatov @kateinoigakukun @j-f1 

I couldn't find any local file that defines `"javascript_kit": "swjs_create_typed_array"` so I don't know how to start debugging this, unfortunately :(

**Comment by MaxDesiatov** [comment] 2022-04-27 13:44
@ephemer could you clarify which version of `carton` you're using? Also, with regards to JavaScriptKit, the latest version is 0.14.0. Would you be able to confirm that the error is still reproducible for you with the latest versions of `carton` and JavaScriptKit?

**Comment by ephemer** [comment] 2022-04-28 13:00
I'm using the latest version of everything AFAIK: I just started using the entire SwiftWasm ecosystem this week. Will double check and edit this post if not

**Comment by kateinoigakukun** [comment] 2022-04-28 13:10
The default environment of `carton test` is command-line mode, so JSKit doesn't work. Please use `carton test --environment defaultBrowser` instead.

**Comment by MaxDesiatov** [comment] 2022-04-28 13:11
Should we close this as a duplicate of https://github.com/swiftwasm/WasmTransformer/issues/18 then?

**Comment by kateinoigakukun** [comment] 2022-04-28 13:15
Or we maybe have to provide a way to test with Node.js

**Comment by ephemer** [comment] 2022-05-03 10:00
Thanks a lot for your responses here! That clears things up.

I would be totally fine with avoiding JSKit in the tests. More than anything, this Issue laments the fact that it's not obvious that we have to do that. The issue is that `carton init; carton test` breaks, and that is pretty confusing unless you happen to know about the issue and about the `carton test --environment defaultBrowser` option.

Ideally the error reporting would make this clear – at the moment it's impossible to even know where to start to look.

**Closed** 2022-05-11 14:40 UTC
Labels: question
